# Generated by Django 5.2.6 on 2025-10-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('ma_bn', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=100)),
                ('hinh_anh', models.ImageField(upload_to='banner/')),
                ('ngay_bd', models.DateField()),
                ('ngay_kt', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('ma_kh', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sdt', models.CharField(max_length=15, unique=True)),
                ('dia_chi', models.CharField(max_length=255)),
                ('ten_dang_nhap', models.CharField(max_length=50, unique=True)),
                ('mat_khau', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('ma_km', models.AutoField(primary_key=True, serialize=False)),
                ('ten_km', models.CharField(max_length=100)),
                ('mo_ta', models.TextField()),
                ('ngay_bd', models.DateField()),
                ('ngay_kt', models.DateField()),
                ('gia_tri_giam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ap_dung_cho', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuanTri',
            fields=[
                ('ma_qt', models.AutoField(primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ten_dang_nhap', models.CharField(max_length=50, unique=True)),
                ('mat_khau', models.CharField(max_length=255)),
                ('vai_tro', models.CharField(default='admin', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('ma_sp', models.AutoField(primary_key=True, serialize=False)),
                ('ten_sp', models.CharField(max_length=100)),
                ('hang_sx', models.CharField(max_length=100)),
                ('gia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('thong_so', models.TextField(blank=True, null=True)),
                ('ngay_nhap', models.DateField()),
                ('tinh_trang', models.CharField(max_length=50)),
                ('so_luong_ton', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('ma_gh', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giohang', to='api.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_dh', models.CharField(max_length=20, unique=True)),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trang_thai', models.CharField(default='Chờ xử lý', max_length=50)),
                ('dia_chi_giao', models.CharField(max_length=255)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='don_hang', to='api.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('ma_bc', models.AutoField(primary_key=True, serialize=False)),
                ('loai_bao_cao', models.CharField(max_length=100)),
                ('thoi_gian', models.DateTimeField()),
                ('noi_dung', models.TextField()),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.quantri')),
            ],
        ),
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='sanpham/')),
                ('mo_ta', models.CharField(blank=True, max_length=255, null=True)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hinh_anh_list', to='api.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('ma_dgia', models.AutoField(primary_key=True, serialize=False)),
                ('so_sao', models.IntegerField()),
                ('noi_dung', models.TextField(blank=True, null=True)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='danhgia/')),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='api.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('ma_tt', models.AutoField(primary_key=True, serialize=False)),
                ('phuong_thuc', models.CharField(max_length=50)),
                ('trang_thai_tt', models.CharField(default='Chưa thanh toán', max_length=50)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.donhang')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietGio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=1)),
                ('gio_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='api.giohang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
            options={
                'unique_together': {('gio_hang', 'san_pham')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietDH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('thanh_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='api.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
            options={
                'unique_together': {('don_hang', 'san_pham')},
            },
        ),
        migrations.CreateModel(
            name='YeuThich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_them', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.khachhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sanpham')),
            ],
            options={
                'unique_together': {('khach_hang', 'san_pham')},
            },
        ),
    ]
